import {
  AvailabilityRecurrence,
  PrismaClient,
  SessionModality,
  SpecializationType,
  UserRole,
} from '@prisma/client';
import { hashSync } from 'bcryptjs';

const prisma = new PrismaClient();
const SEED_PASSWORD = hashSync('seed-password-123', 10);

interface ProfSeed {
  email: string;
  name: string;
  bio: string;
  areaSlugs: string[];
  modalities: SessionModality[];
  yearsExperience: number;
  averageRating: number;
  totalReviews: number;
  priceMin: number;
  priceMax: number;
  city: string;
  state: string;
  isVerified: boolean;
  isAcceptingClients?: boolean;
  crefNumber?: string;
  sessionDurationMinutes?: number;
}

const PROFESSIONALS: ProfSeed[] = [
  {
    email: 'lucas.personal@fitmatch.dev',
    name: 'Lucas Ferreira',
    bio: 'Personal trainer especializado em hipertrofia e definição muscular. Atendo em academia parceira e online.',
    areaSlugs: ['PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 6,
    averageRating: 4.8,
    totalReviews: 64,
    priceMin: 100,
    priceMax: 160,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    crefNumber: '012345-G/SP',
    sessionDurationMinutes: 60,
  },
  {
    email: 'beatriz.personal@fitmatch.dev',
    name: 'Beatriz Alves',
    bio: 'Personal trainer focada em emagrecimento feminino e condicionamento funcional. Atendo na zona norte de SP.',
    areaSlugs: ['PERSONAL_TRAINING', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 4,
    averageRating: 4.7,
    totalReviews: 38,
    priceMin: 90,
    priceMax: 140,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    crefNumber: '022345-G/SP',
    sessionDurationMinutes: 60,
  },
  {
    email: 'thiago.strength@fitmatch.dev',
    name: 'Thiago Barbosa',
    bio: 'Coach de força e powerlifting, experiência em competições nacionais. Treinos individualizados e periodização avançada.',
    areaSlugs: ['PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 9,
    averageRating: 4.9,
    totalReviews: 102,
    priceMin: 150,
    priceMax: 220,
    city: 'Campinas',
    state: 'SP',
    isVerified: true,
    crefNumber: '032345-G/SP',
    sessionDurationMinutes: 75,
  },
  {
    email: 'carolina.online@fitmatch.dev',
    name: 'Carolina Mendes',
    bio: 'Personal online com metodologia exclusiva para alunos que treinam em casa. Planilhas e acompanhamento semanal.',
    areaSlugs: ['PERSONAL_TRAINING'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 3,
    averageRating: 4.6,
    totalReviews: 29,
    priceMin: 70,
    priceMax: 110,
    city: 'Florianópolis',
    state: 'SC',
    isVerified: false,
    sessionDurationMinutes: 50,
  },
  {
    email: 'rodrigo.atletismo@fitmatch.dev',
    name: 'Rodrigo Costa',
    bio: 'Ex-atleta olímpico reconvertido em personal. Especialidade em preparação física para esportes competitivos.',
    areaSlugs: ['PERSONAL_TRAINING', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 14,
    averageRating: 4.95,
    totalReviews: 180,
    priceMin: 200,
    priceMax: 300,
    city: 'Rio de Janeiro',
    state: 'RJ',
    isVerified: true,
    crefNumber: '042345-G/RJ',
    sessionDurationMinutes: 90,
  },
  {
    email: 'fernanda.senior@fitmatch.dev',
    name: 'Fernanda Rocha',
    bio: 'Especialista em treinamento para terceira idade e reabilitação pós-cirúrgica. Atendimento domiciliar disponível.',
    areaSlugs: ['PERSONAL_TRAINING', 'REHABILITATION'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 11,
    averageRating: 4.85,
    totalReviews: 93,
    priceMin: 130,
    priceMax: 190,
    city: 'Belo Horizonte',
    state: 'MG',
    isVerified: true,
    crefNumber: '052345-G/MG',
    sessionDurationMinutes: 60,
  },
  {
    email: 'gabriel.hiit@fitmatch.dev',
    name: 'Gabriel Nunes',
    bio: 'Personal especializado em HIIT e treinos metabólicos. Transformação em 12 semanas com método comprovado.',
    areaSlugs: ['PERSONAL_TRAINING', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.ONLINE, SessionModality.HYBRID],
    yearsExperience: 5,
    averageRating: 4.7,
    totalReviews: 51,
    priceMin: 85,
    priceMax: 130,
    city: 'Fortaleza',
    state: 'CE',
    isVerified: true,
    sessionDurationMinutes: 45,
  },
  {
    email: 'isabela.bodybuilding@fitmatch.dev',
    name: 'Isabela Freitas',
    bio: 'Fisiculturista profissional e personal trainer. Foco em estética, hipertrofia e preparação para competições.',
    areaSlugs: ['PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 7,
    averageRating: 4.8,
    totalReviews: 75,
    priceMin: 120,
    priceMax: 180,
    city: 'Curitiba',
    state: 'PR',
    isVerified: true,
    crefNumber: '062345-G/PR',
    sessionDurationMinutes: 60,
  },
  {
    email: 'paulo.bootcamp@fitmatch.dev',
    name: 'Paulo Guimarães',
    bio: 'Coach de bootcamp ao ar livre e personal. Treinos em grupo pequeno e individuais no Parque Ibirapuera.',
    areaSlugs: ['PERSONAL_TRAINING', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 8,
    averageRating: 4.75,
    totalReviews: 88,
    priceMin: 80,
    priceMax: 140,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    crefNumber: '072345-G/SP',
    sessionDurationMinutes: 60,
  },
  {
    email: 'natalia.corrida@fitmatch.dev',
    name: 'Natália Cardoso',
    bio: 'Personal com especialização em corrida e maratona. Preparação para provas de 5k a ultramaratonas.',
    areaSlugs: ['PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 6,
    averageRating: 4.9,
    totalReviews: 67,
    priceMin: 110,
    priceMax: 160,
    city: 'Porto Alegre',
    state: 'RS',
    isVerified: true,
    crefNumber: '082345-G/RS',
    sessionDurationMinutes: 60,
  },
  {
    email: 'andre.personal.sp@fitmatch.dev',
    name: 'André Lima',
    bio: 'Personal trainer com foco em perda de peso e qualidade de vida. Metodologia baseada em evidências científicas.',
    areaSlugs: ['PERSONAL_TRAINING', 'NUTRITION_COACHING'],
    modalities: [SessionModality.HYBRID],
    yearsExperience: 5,
    averageRating: 4.65,
    totalReviews: 44,
    priceMin: 95,
    priceMax: 150,
    city: 'Ribeirão Preto',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'vanessa.gravida@fitmatch.dev',
    name: 'Vanessa Campos',
    bio: 'Personal especializada em gestantes e pós-parto. Treinos seguros e eficazes para cada fase da maternidade.',
    areaSlugs: ['PERSONAL_TRAINING', 'REHABILITATION'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 8,
    averageRating: 4.9,
    totalReviews: 110,
    priceMin: 120,
    priceMax: 170,
    city: 'Brasília',
    state: 'DF',
    isVerified: true,
    crefNumber: '092345-G/DF',
    sessionDurationMinutes: 55,
  },
  {
    email: 'enzo.personal@fitmatch.dev',
    name: 'Enzo Marques',
    bio: 'Jovem personal com foco em adolescentes e jovens adultos. Treinos desafiadores com linguagem próxima ao público jovem.',
    areaSlugs: ['PERSONAL_TRAINING', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 2,
    averageRating: 4.5,
    totalReviews: 19,
    priceMin: 70,
    priceMax: 110,
    city: 'Salvador',
    state: 'BA',
    isVerified: false,
    sessionDurationMinutes: 60,
  },
  {
    email: 'karina.tenis@fitmatch.dev',
    name: 'Karina Pinto',
    bio: 'Preparação física específica para tenistas amadores e profissionais. Especialização em agilidade e explosão.',
    areaSlugs: ['PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 10,
    averageRating: 4.8,
    totalReviews: 82,
    priceMin: 160,
    priceMax: 230,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    crefNumber: '102345-G/SP',
    sessionDurationMinutes: 60,
  },
  {
    email: 'caio.personal.rj@fitmatch.dev',
    name: 'Caio Teixeira',
    bio: 'Personal com abordagem holística — une treino físico, mindset e nutrição. Transformação completa em 3 meses.',
    areaSlugs: ['PERSONAL_TRAINING', 'NUTRITION_COACHING'],
    modalities: [SessionModality.HYBRID, SessionModality.ONLINE],
    yearsExperience: 7,
    averageRating: 4.85,
    totalReviews: 96,
    priceMin: 130,
    priceMax: 200,
    city: 'Rio de Janeiro',
    state: 'RJ',
    isVerified: true,
    crefNumber: '112345-G/RJ',
    sessionDurationMinutes: 70,
  },

  {
    email: 'diego.funcional@fitmatch.dev',
    name: 'Diego Santana',
    bio: 'Treinamento funcional para ganho de mobilidade e prevenção de lesões. Aulas individuais e em dupla.',
    areaSlugs: ['FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 6,
    averageRating: 4.7,
    totalReviews: 58,
    priceMin: 95,
    priceMax: 145,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'julia.funcional@fitmatch.dev',
    name: 'Júlia Castro',
    bio: 'Funcional online ao vivo. Aulas dinâmicas com pouco ou nenhum equipamento, adaptadas para casa ou parque.',
    areaSlugs: ['FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 4,
    averageRating: 4.6,
    totalReviews: 33,
    priceMin: 65,
    priceMax: 100,
    city: 'Goiânia',
    state: 'GO',
    isVerified: false,
    sessionDurationMinutes: 45,
  },
  {
    email: 'victor.trf@fitmatch.dev',
    name: 'Victor Azevedo',
    bio: 'Coach de movimento e mobilidade funcional. Especialista em TRX e suspensão. Atendo empresas e academia.',
    areaSlugs: ['FUNCTIONAL_TRAINING', 'REHABILITATION'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 8,
    averageRating: 4.8,
    totalReviews: 72,
    priceMin: 110,
    priceMax: 165,
    city: 'Curitiba',
    state: 'PR',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'aline.funcional@fitmatch.dev',
    name: 'Aline Reis',
    bio: 'Treinamento funcional voltado para mulheres acima de 40. Foco em saúde óssea, equilíbrio e vitalidade.',
    areaSlugs: ['FUNCTIONAL_TRAINING', 'PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 9,
    averageRating: 4.85,
    totalReviews: 104,
    priceMin: 100,
    priceMax: 155,
    city: 'Belo Horizonte',
    state: 'MG',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'henrique.funcional@fitmatch.dev',
    name: 'Henrique Vieira',
    bio: 'Funcional e calistenia avançada. Treinos de movimento corporal para nível intermediário e avançado.',
    areaSlugs: ['FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 5,
    averageRating: 4.75,
    totalReviews: 49,
    priceMin: 90,
    priceMax: 140,
    city: 'Recife',
    state: 'PE',
    isVerified: true,
    sessionDurationMinutes: 60,
  },

  {
    email: 'pedro.crossfit@fitmatch.dev',
    name: 'Pedro Carvalho',
    bio: 'Head coach de box CrossFit com 10 anos de experiência. Atendo atletas de competição e iniciantes.',
    areaSlugs: ['CROSSFIT', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 10,
    averageRating: 4.9,
    totalReviews: 135,
    priceMin: 140,
    priceMax: 200,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    crefNumber: '122345-G/SP',
    sessionDurationMinutes: 60,
  },
  {
    email: 'larissa.crossfit@fitmatch.dev',
    name: 'Larissa Monteiro',
    bio: 'CrossFit L2 certified coach. Especialista em ginástica olímpica aplicada ao CrossFit. Box na zona leste de SP.',
    areaSlugs: ['CROSSFIT'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 7,
    averageRating: 4.8,
    totalReviews: 88,
    priceMin: 130,
    priceMax: 190,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'igor.crossfit.rio@fitmatch.dev',
    name: 'Igor Moraes',
    bio: 'CrossFit e levantamento olímpico. Campeão estadual RJ 2022. Treinos individuais e WODs personalizados.',
    areaSlugs: ['CROSSFIT', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 11,
    averageRating: 4.85,
    totalReviews: 119,
    priceMin: 160,
    priceMax: 240,
    city: 'Rio de Janeiro',
    state: 'RJ',
    isVerified: true,
    crefNumber: '132345-G/RJ',
    sessionDurationMinutes: 75,
  },
  {
    email: 'sabrina.crossfit@fitmatch.dev',
    name: 'Sabrina Lopes',
    bio: 'Coach CrossFit focada em iniciantes e pessoas com medo de começar. Progressão segura e acolhedora.',
    areaSlugs: ['CROSSFIT', 'PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 5,
    averageRating: 4.7,
    totalReviews: 56,
    priceMin: 100,
    priceMax: 160,
    city: 'Campinas',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'alexandre.wod@fitmatch.dev',
    name: 'Alexandre Borges',
    bio: 'CrossFit e condicionamento físico geral. Programação individualizada para atletas masters (acima de 35 anos).',
    areaSlugs: ['CROSSFIT'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 9,
    averageRating: 4.75,
    totalReviews: 91,
    priceMin: 135,
    priceMax: 195,
    city: 'Porto Alegre',
    state: 'RS',
    isVerified: true,
    sessionDurationMinutes: 60,
  },

  {
    email: 'renata.pilates@fitmatch.dev',
    name: 'Renata Sousa',
    bio: 'Pilates clássico e contemporâneo no estúdio ou online. Especialidade em dor lombar crônica e hérnia de disco.',
    areaSlugs: ['PILATES', 'REHABILITATION'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 12,
    averageRating: 4.95,
    totalReviews: 156,
    priceMin: 130,
    priceMax: 200,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 55,
  },
  {
    email: 'amanda.pilates.curitiba@fitmatch.dev',
    name: 'Amanda Ferreira',
    bio: 'Pilates no aparelho e solo. Foco em fortalecimento do core e melhora postural para sedentários.',
    areaSlugs: ['PILATES'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 6,
    averageRating: 4.8,
    totalReviews: 73,
    priceMin: 120,
    priceMax: 175,
    city: 'Curitiba',
    state: 'PR',
    isVerified: true,
    sessionDurationMinutes: 55,
  },
  {
    email: 'denise.pilates.bh@fitmatch.dev',
    name: 'Denise Oliveira',
    bio: 'Fisioterapeuta e instrutora de Pilates clínico. Reabilitação de joelho, ombro e coluna vertebral.',
    areaSlugs: ['PILATES', 'REHABILITATION'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 15,
    averageRating: 4.9,
    totalReviews: 202,
    priceMin: 150,
    priceMax: 220,
    city: 'Belo Horizonte',
    state: 'MG',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'tatiana.pilates.online@fitmatch.dev',
    name: 'Tatiana Correia',
    bio: 'Pilates solo online ao vivo. Aulas individuais e pequenos grupos. Excelente custo-benefício.',
    areaSlugs: ['PILATES'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 7,
    averageRating: 4.7,
    totalReviews: 84,
    priceMin: 80,
    priceMax: 130,
    city: 'Natal',
    state: 'RN',
    isVerified: true,
    sessionDurationMinutes: 50,
  },
  {
    email: 'sergio.pilates@fitmatch.dev',
    name: 'Sérgio Mesquita',
    bio: 'Pilates para homens — quebrando o preconceito. Treino de força e flexibilidade integrados no aparelho.',
    areaSlugs: ['PILATES', 'PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 8,
    averageRating: 4.8,
    totalReviews: 61,
    priceMin: 140,
    priceMax: 190,
    city: 'Rio de Janeiro',
    state: 'RJ',
    isVerified: true,
    sessionDurationMinutes: 55,
  },

  {
    email: 'mariana.yoga.sp@fitmatch.dev',
    name: 'Mariana Alves',
    bio: 'Yoga Hatha e Vinyasa, experiência em retiros e formação no exterior. Aulas individuais e pequenos grupos.',
    areaSlugs: ['YOGA', 'MEDITATION'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 12,
    averageRating: 4.95,
    totalReviews: 198,
    priceMin: 100,
    priceMax: 160,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 75,
  },
  {
    email: 'bruna.yoga.floripa@fitmatch.dev',
    name: 'Bruna Nascimento',
    bio: 'Yoga Yin e restaurativo para alívio do estresse e ansiedade. Abordagem terapêutica e personalizada.',
    areaSlugs: ['YOGA', 'MEDITATION'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 8,
    averageRating: 4.9,
    totalReviews: 127,
    priceMin: 90,
    priceMax: 140,
    city: 'Florianópolis',
    state: 'SC',
    isVerified: true,
    sessionDurationMinutes: 75,
  },
  {
    email: 'otavio.yoga.online@fitmatch.dev',
    name: 'Otávio Rezende',
    bio: 'Ashtanga yoga online. Práticas para todos os níveis com ajustes verbais e acompanhamento individual.',
    areaSlugs: ['YOGA'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 10,
    averageRating: 4.85,
    totalReviews: 143,
    priceMin: 70,
    priceMax: 120,
    city: 'Fortaleza',
    state: 'CE',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'elisa.yoga.power@fitmatch.dev',
    name: 'Elisa Torres',
    bio: 'Power Yoga e Yoga para atletas. Integra mobilidade e força para melhorar desempenho esportivo.',
    areaSlugs: ['YOGA', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 7,
    averageRating: 4.8,
    totalReviews: 89,
    priceMin: 95,
    priceMax: 150,
    city: 'Curitiba',
    state: 'PR',
    isVerified: true,
    sessionDurationMinutes: 70,
  },
  {
    email: 'felipe.yoga.bh@fitmatch.dev',
    name: 'Felipe Magalhães',
    bio: 'Yoga tradicional baseado nos textos clássicos. Aulas individuais com filosofia, meditação e prática física.',
    areaSlugs: ['YOGA', 'MEDITATION'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 15,
    averageRating: 4.9,
    totalReviews: 221,
    priceMin: 110,
    priceMax: 170,
    city: 'Belo Horizonte',
    state: 'MG',
    isVerified: true,
    sessionDurationMinutes: 90,
  },
  {
    email: 'patricia.yoga.rj@fitmatch.dev',
    name: 'Patrícia Duarte',
    bio: 'Kundalini yoga e terapia holística. Atendo presencialmente no Rio e online para todo o Brasil.',
    areaSlugs: ['YOGA', 'MEDITATION'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 18,
    averageRating: 4.95,
    totalReviews: 267,
    priceMin: 120,
    priceMax: 180,
    city: 'Rio de Janeiro',
    state: 'RJ',
    isVerified: true,
    sessionDurationMinutes: 75,
  },

  {
    email: 'camila.meditacao@fitmatch.dev',
    name: 'Camila Rodrigues',
    bio: 'Coach de meditação e mindfulness para executivos e universitários. Programa de 8 semanas com resultados comprovados.',
    areaSlugs: ['MEDITATION'],
    modalities: [SessionModality.ONLINE, SessionModality.HYBRID],
    yearsExperience: 6,
    averageRating: 4.8,
    totalReviews: 94,
    priceMin: 80,
    priceMax: 130,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 40,
  },
  {
    email: 'davi.mindfulness@fitmatch.dev',
    name: 'Davi Pacheco',
    bio: 'Meditação budista e MBSR (Mindfulness Based Stress Reduction). Práticas individuais e em grupo.',
    areaSlugs: ['MEDITATION', 'YOGA'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 14,
    averageRating: 4.9,
    totalReviews: 176,
    priceMin: 90,
    priceMax: 140,
    city: 'Brasília',
    state: 'DF',
    isVerified: true,
    sessionDurationMinutes: 50,
  },
  {
    email: 'leticia.meditacao@fitmatch.dev',
    name: 'Letícia Fonseca',
    bio: 'Meditação guiada para ansiedade, insônia e estresse. Sessões suaves e acolhedoras para iniciantes.',
    areaSlugs: ['MEDITATION'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 4,
    averageRating: 4.7,
    totalReviews: 47,
    priceMin: 60,
    priceMax: 100,
    city: 'Salvador',
    state: 'BA',
    isVerified: false,
    sessionDurationMinutes: 35,
  },

  {
    email: 'carlos.bjj@fitmatch.dev',
    name: 'Carlos Figueiredo',
    bio: 'Faixa coral de BJJ com mais de 20 anos de experiência. Aulas individuais e seminários para todos os níveis.',
    areaSlugs: ['MARTIAL_ARTS'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 20,
    averageRating: 4.95,
    totalReviews: 243,
    priceMin: 180,
    priceMax: 260,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 90,
  },
  {
    email: 'juliana.muaythai@fitmatch.dev',
    name: 'Juliana Barros',
    bio: 'Muay Thai feminino e defesa pessoal. Campeã sul-americana 2019. Aulas presenciais e análise de vídeo online.',
    areaSlugs: ['MARTIAL_ARTS'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 13,
    averageRating: 4.9,
    totalReviews: 161,
    priceMin: 150,
    priceMax: 220,
    city: 'Curitiba',
    state: 'PR',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'wagner.judo@fitmatch.dev',
    name: 'Wagner Ribeiro',
    bio: 'Judoca olímpico e professor certificado. Judô técnico e competitivo para crianças, jovens e adultos.',
    areaSlugs: ['MARTIAL_ARTS'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 18,
    averageRating: 4.85,
    totalReviews: 132,
    priceMin: 130,
    priceMax: 200,
    city: 'Rio de Janeiro',
    state: 'RJ',
    isVerified: true,
    sessionDurationMinutes: 90,
  },
  {
    email: 'debora.karate@fitmatch.dev',
    name: 'Débora Neto',
    bio: 'Karatê Shotokan faixa preta 3º dan. Treino de kata e kumitê para iniciantes e competidores.',
    areaSlugs: ['MARTIAL_ARTS', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 16,
    averageRating: 4.8,
    totalReviews: 108,
    priceMin: 120,
    priceMax: 180,
    city: 'Belo Horizonte',
    state: 'MG',
    isVerified: true,
    sessionDurationMinutes: 75,
  },
  {
    email: 'nicolas.boxe@fitmatch.dev',
    name: 'Nicolas Guerra',
    bio: 'Boxe técnico e condicionamento físico. Ex-profissional da categoria super pena. Aulas individuais focadas em técnica.',
    areaSlugs: ['MARTIAL_ARTS', 'PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 12,
    averageRating: 4.75,
    totalReviews: 78,
    priceMin: 140,
    priceMax: 210,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },

  {
    email: 'marina.natacao@fitmatch.dev',
    name: 'Marina Batista',
    bio: 'Ex-nadadora olímpica reconvertida em professora particular. Técnica avançada para adultos iniciantes e intermediários.',
    areaSlugs: ['SWIMMING'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 9,
    averageRating: 4.95,
    totalReviews: 148,
    priceMin: 150,
    priceMax: 220,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 50,
  },
  {
    email: 'roberto.natacao@fitmatch.dev',
    name: 'Roberto Paixão',
    bio: 'Natação terapêutica e hidroginástica para reabilitação. Trabalha com pessoas com mobilidade reduzida e idosos.',
    areaSlugs: ['SWIMMING', 'REHABILITATION'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 11,
    averageRating: 4.85,
    totalReviews: 122,
    priceMin: 120,
    priceMax: 180,
    city: 'Recife',
    state: 'PE',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'alessandra.natacao@fitmatch.dev',
    name: 'Alessandra Cruz',
    bio: 'Técnica dos 4 estilos para adultos. Especialidade em medo da água e adultos que nunca nadaram.',
    areaSlugs: ['SWIMMING'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 7,
    averageRating: 4.9,
    totalReviews: 99,
    priceMin: 130,
    priceMax: 190,
    city: 'Rio de Janeiro',
    state: 'RJ',
    isVerified: true,
    sessionDurationMinutes: 50,
  },
  {
    email: 'marcos.triathlon@fitmatch.dev',
    name: 'Marcos Drumond',
    bio: 'Treinamento para triathlon com ênfase em natação. Preparação para provas sprint, olímpica e Ironman.',
    areaSlugs: ['SWIMMING', 'CYCLING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 14,
    averageRating: 4.9,
    totalReviews: 173,
    priceMin: 170,
    priceMax: 250,
    city: 'Florianópolis',
    state: 'SC',
    isVerified: true,
    sessionDurationMinutes: 75,
  },

  // ─── CYCLING (8) ──────────────────────────────────────────────────────────
  {
    email: 'bruno.ciclismo@fitmatch.dev',
    name: 'Bruno Vasconcelos',
    bio: 'Coach de ciclismo de estrada e MTB. Periodização com potenciômetro e análise de dados de treino.',
    areaSlugs: ['CYCLING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 10,
    averageRating: 4.85,
    totalReviews: 115,
    priceMin: 130,
    priceMax: 200,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'andreia.spinning@fitmatch.dev',
    name: 'Andréia Melo',
    bio: 'Instrutora de spinning indoor certificada. Aulas motivadoras com playlist premium e foco em queima calórica.',
    areaSlugs: ['CYCLING', 'PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 6,
    averageRating: 4.8,
    totalReviews: 86,
    priceMin: 80,
    priceMax: 130,
    city: 'Brasília',
    state: 'DF',
    isVerified: true,
    sessionDurationMinutes: 45,
  },
  {
    email: 'leandro.bike@fitmatch.dev',
    name: 'Leandro Faria',
    bio: 'Ciclismo urbano e bikefitting. Ajuste biomecânico completo para melhorar performance e prevenir lesões.',
    areaSlugs: ['CYCLING', 'REHABILITATION'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 8,
    averageRating: 4.75,
    totalReviews: 67,
    priceMin: 140,
    priceMax: 200,
    city: 'Campinas',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 90,
  },
  {
    email: 'simone.ciclismo@fitmatch.dev',
    name: 'Simone Tavares',
    bio: 'Coach de ciclismo para mulheres. Grupos de treino e planilhas individuais para iniciantes e intermediárias.',
    areaSlugs: ['CYCLING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 5,
    averageRating: 4.7,
    totalReviews: 41,
    priceMin: 100,
    priceMax: 150,
    city: 'Porto Alegre',
    state: 'RS',
    isVerified: true,
    sessionDurationMinutes: 60,
  },

  // ─── DANCE (8) ────────────────────────────────────────────────────────────
  {
    email: 'eduarda.samba@fitmatch.dev',
    name: 'Eduarda Conceição',
    bio: 'Samba de gafieira e pagode baiano. Aulas individuais e em casal. Preparo para casamentos e eventos.',
    areaSlugs: ['DANCE'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 9,
    averageRating: 4.9,
    totalReviews: 137,
    priceMin: 100,
    priceMax: 160,
    city: 'Salvador',
    state: 'BA',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'rafael.danca.sp@fitmatch.dev',
    name: 'Rafael Andrade',
    bio: 'Street dance, hip hop e breaking. Professor com experiência em competições internacionais e shows.',
    areaSlugs: ['DANCE'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 12,
    averageRating: 4.85,
    totalReviews: 151,
    priceMin: 110,
    priceMax: 170,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'priscila.zumba@fitmatch.dev',
    name: 'Priscila Menezes',
    bio: 'Instrutora Zumba certificada e fitdance. Aulas energéticas para emagrecimento e bem-estar.',
    areaSlugs: ['DANCE', 'PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 7,
    averageRating: 4.8,
    totalReviews: 112,
    priceMin: 80,
    priceMax: 130,
    city: 'Fortaleza',
    state: 'CE',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'cristiano.ballet@fitmatch.dev',
    name: 'Cristiano Ramos',
    bio: 'Ballet clássico para adultos iniciantes. Técnica, postura e expressão artística em ambiente acolhedor.',
    areaSlugs: ['DANCE'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 15,
    averageRating: 4.9,
    totalReviews: 189,
    priceMin: 120,
    priceMax: 180,
    city: 'Rio de Janeiro',
    state: 'RJ',
    isVerified: true,
    sessionDurationMinutes: 75,
  },
  {
    email: 'flavia.danca.online@fitmatch.dev',
    name: 'Flávia Nunes',
    bio: 'Dança contemporânea e jazz online. Aulas coreografadas com trilha sonora pop para treinar em casa.',
    areaSlugs: ['DANCE'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 8,
    averageRating: 4.75,
    totalReviews: 68,
    priceMin: 70,
    priceMax: 110,
    city: 'Recife',
    state: 'PE',
    isVerified: false,
    sessionDurationMinutes: 50,
  },

  // ─── NUTRITION COACHING (8) ───────────────────────────────────────────────
  {
    email: 'patricia.nutri@fitmatch.dev',
    name: 'Patrícia Aguiar',
    bio: 'Nutricionista esportiva parceira de personal trainers. Planos individualizados integrados ao treino.',
    areaSlugs: ['NUTRITION_COACHING'],
    modalities: [SessionModality.ONLINE, SessionModality.HYBRID],
    yearsExperience: 9,
    averageRating: 4.9,
    totalReviews: 145,
    priceMin: 150,
    priceMax: 220,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'henrique.nutri.sp@fitmatch.dev',
    name: 'Henrique Amorim',
    bio: 'Nutrição plant-based para atletas. Especialidade em dieta vegana e vegetariana com alta performance.',
    areaSlugs: ['NUTRITION_COACHING'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 6,
    averageRating: 4.8,
    totalReviews: 83,
    priceMin: 120,
    priceMax: 180,
    city: 'Curitiba',
    state: 'PR',
    isVerified: true,
    sessionDurationMinutes: 50,
  },
  {
    email: 'ana.nutri.online@fitmatch.dev',
    name: 'Ana Beatriz Santos',
    bio: 'Nutrição clínica e esportiva para emagrecimento sustentável. Sem dietas restritivas, foco em comportamento alimentar.',
    areaSlugs: ['NUTRITION_COACHING'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 4,
    averageRating: 4.75,
    totalReviews: 52,
    priceMin: 100,
    priceMax: 150,
    city: 'Belo Horizonte',
    state: 'MG',
    isVerified: true,
    sessionDurationMinutes: 50,
  },
  {
    email: 'marcio.nutri.hipertrofia@fitmatch.dev',
    name: 'Márcio Esteves',
    bio: 'Nutrição para hipertrofia e competições de fisiculturismo. Protocolo de cutting e bulk para atletas avançados.',
    areaSlugs: ['NUTRITION_COACHING', 'PERSONAL_TRAINING'],
    modalities: [SessionModality.ONLINE, SessionModality.HYBRID],
    yearsExperience: 11,
    averageRating: 4.85,
    totalReviews: 127,
    priceMin: 170,
    priceMax: 250,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },

  {
    email: 'adriana.fisio@fitmatch.dev',
    name: 'Adriana Leal',
    bio: 'Fisioterapeuta esportiva com pós em reabilitação ortopédica. Pós-cirúrgico, LCA, ombro e tornozelo.',
    areaSlugs: ['REHABILITATION'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 13,
    averageRating: 4.95,
    totalReviews: 178,
    priceMin: 180,
    priceMax: 270,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'gustavo.reabilitacao@fitmatch.dev',
    name: 'Gustavo Andrade',
    bio: 'Fisioterapeuta e treinador funcional. Retorno ao esporte após lesões com protocolo gradual e seguro.',
    areaSlugs: ['REHABILITATION', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 10,
    averageRating: 4.9,
    totalReviews: 142,
    priceMin: 160,
    priceMax: 240,
    city: 'Rio de Janeiro',
    state: 'RJ',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'celso.fisio.domiciliar@fitmatch.dev',
    name: 'Celso Brandão',
    bio: 'Fisioterapia domiciliar especializada em pós-AVC, Parkinson e doenças neurodegenerativas.',
    areaSlugs: ['REHABILITATION'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 17,
    averageRating: 4.85,
    totalReviews: 96,
    priceMin: 200,
    priceMax: 280,
    city: 'Belo Horizonte',
    state: 'MG',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'marcia.reabilitacao.pilates@fitmatch.dev',
    name: 'Márcia Silveira',
    bio: 'Pilates clínico para reabilitação de coluna. Hérnia, escoliose e cifose com abordagem conservadora.',
    areaSlugs: ['REHABILITATION', 'PILATES'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 12,
    averageRating: 4.9,
    totalReviews: 154,
    priceMin: 160,
    priceMax: 230,
    city: 'Campinas',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 55,
  },
  {
    email: 'roberto.crossfit.funcional@fitmatch.dev',
    name: 'Roberto Mendes',
    bio: 'CrossFit e funcional para iniciantes com abordagem inclusiva. Sem julgamentos, foco em saúde e bem-estar.',
    areaSlugs: ['CROSSFIT', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 6,
    averageRating: 4.7,
    totalReviews: 53,
    priceMin: 100,
    priceMax: 160,
    city: 'João Pessoa',
    state: 'PB',
    isVerified: false,
    sessionDurationMinutes: 60,
  },
  {
    email: 'luiza.yoga.nutricao@fitmatch.dev',
    name: 'Luiza Pereira',
    bio: 'Yoga e orientação nutricional integrativa. Programa de 30 dias para detox, equilíbrio hormonal e energia.',
    areaSlugs: ['YOGA', 'NUTRITION_COACHING'],
    modalities: [SessionModality.ONLINE, SessionModality.HYBRID],
    yearsExperience: 8,
    averageRating: 4.85,
    totalReviews: 109,
    priceMin: 130,
    priceMax: 190,
    city: 'Manaus',
    state: 'AM',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'tiago.swim.triathlon@fitmatch.dev',
    name: 'Tiago Fontes',
    bio: 'Coach de triathlon completo: natação, ciclismo e corrida. Especialidade em provas Ironman e 70.3.',
    areaSlugs: ['SWIMMING', 'CYCLING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 13,
    averageRating: 4.9,
    totalReviews: 162,
    priceMin: 200,
    priceMax: 300,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 90,
  },
  {
    email: 'fabiana.personal.nutri@fitmatch.dev',
    name: 'Fabiana Queiroz',
    bio: 'Personal trainer e nutricionista. Atendimento completo body & nutrition com planilha integrada.',
    areaSlugs: ['PERSONAL_TRAINING', 'NUTRITION_COACHING'],
    modalities: [SessionModality.HYBRID, SessionModality.ONLINE],
    yearsExperience: 7,
    averageRating: 4.8,
    totalReviews: 78,
    priceMin: 160,
    priceMax: 240,
    city: 'Porto Alegre',
    state: 'RS',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'clauber.artes.marciais@fitmatch.dev',
    name: 'Clauber Rocha',
    bio: 'Mestre de capoeira angola e regional. Aulas individuais e em grupo para adultos e crianças.',
    areaSlugs: ['MARTIAL_ARTS', 'DANCE'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 22,
    averageRating: 4.9,
    totalReviews: 214,
    priceMin: 120,
    priceMax: 180,
    city: 'Salvador',
    state: 'BA',
    isVerified: true,
    sessionDurationMinutes: 75,
  },
  {
    email: 'cristiane.pilates.yoga@fitmatch.dev',
    name: 'Cristiane Lemos',
    bio: 'Pilates e yoga integrados para flexibilidade e força profunda. Programa de 6 semanas para desk workers.',
    areaSlugs: ['PILATES', 'YOGA'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 9,
    averageRating: 4.85,
    totalReviews: 117,
    priceMin: 130,
    priceMax: 195,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'anderson.funcional.danca@fitmatch.dev',
    name: 'Anderson Lima',
    bio: 'Treinamento funcional com elementos de dança afro. Aulas divertidas que mesclam condicionamento e cultura.',
    areaSlugs: ['FUNCTIONAL_TRAINING', 'DANCE'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 5,
    averageRating: 4.75,
    totalReviews: 44,
    priceMin: 90,
    priceMax: 140,
    city: 'Recife',
    state: 'PE',
    isVerified: false,
    sessionDurationMinutes: 60,
  },
  {
    email: 'stephanie.meditacao.yoga@fitmatch.dev',
    name: 'Stephanie Moura',
    bio: 'Yoga nidra e meditação para insônia crônica e burnout. Programa terapêutico de 10 sessões.',
    areaSlugs: ['MEDITATION', 'YOGA'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 7,
    averageRating: 4.9,
    totalReviews: 133,
    priceMin: 100,
    priceMax: 150,
    city: 'Brasília',
    state: 'DF',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'nico.boxe.condicionamento@fitmatch.dev',
    name: 'Nicolau Serra',
    bio: 'Boxe para condicionamento físico (não competitivo). Ótimo para estresse, emagrecimento e autoconfiança.',
    areaSlugs: ['MARTIAL_ARTS', 'PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 8,
    averageRating: 4.8,
    totalReviews: 96,
    priceMin: 110,
    priceMax: 165,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'sueli.natacao.bebe@fitmatch.dev',
    name: 'Sueli Monteiro',
    bio: 'Natação para bebês, crianças e adultos com hidrofobia. Método carinhoso e gradual de adaptação aquática.',
    areaSlugs: ['SWIMMING'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 14,
    averageRating: 4.95,
    totalReviews: 208,
    priceMin: 140,
    priceMax: 200,
    city: 'Campinas',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 45,
  },
  {
    email: 'renan.speed.cycling@fitmatch.dev',
    name: 'Renan Vieira',
    bio: 'Coach de velocidade e sprint no ciclismo. Preparação para provas de critério e circuito.',
    areaSlugs: ['CYCLING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 9,
    averageRating: 4.8,
    totalReviews: 74,
    priceMin: 145,
    priceMax: 210,
    city: 'Rio de Janeiro',
    state: 'RJ',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'bianca.danca.urbana@fitmatch.dev',
    name: 'Bianca Fernandes',
    bio: 'Danças urbanas e tutoriais de coreografia online. Atendo presencialmente em SP e pelo Zoom.',
    areaSlugs: ['DANCE'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 6,
    averageRating: 4.7,
    totalReviews: 61,
    priceMin: 85,
    priceMax: 130,
    city: 'São Paulo',
    state: 'SP',
    isVerified: false,
    sessionDurationMinutes: 55,
  },
  {
    email: 'marcos.rehab.esportivo@fitmatch.dev',
    name: 'Marcos Brandão',
    bio: 'Reabilitação esportiva e prevenção de lesões para corredores de rua. Avaliação biomecânica completa.',
    areaSlugs: ['REHABILITATION', 'PERSONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 11,
    averageRating: 4.9,
    totalReviews: 138,
    priceMin: 190,
    priceMax: 260,
    city: 'Curitiba',
    state: 'PR',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'luara.nutri.esportiva@fitmatch.dev',
    name: 'Luara Azevedo',
    bio: 'Nutricionista esportiva focada em mulheres com síndrome dos ovários policísticos e resistência hormonal.',
    areaSlugs: ['NUTRITION_COACHING'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 6,
    averageRating: 4.85,
    totalReviews: 97,
    priceMin: 140,
    priceMax: 200,
    city: 'Goiânia',
    state: 'GO',
    isVerified: true,
    sessionDurationMinutes: 50,
  },
  {
    email: 'daniel.funcional.online@fitmatch.dev',
    name: 'Daniel Souza',
    bio: 'Treinamento funcional 100% online ao vivo. Mínimo de equipamentos, máximo de resultados em 30 min/dia.',
    areaSlugs: ['FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 4,
    averageRating: 4.65,
    totalReviews: 38,
    priceMin: 60,
    priceMax: 95,
    city: 'São Luis',
    state: 'MA',
    isVerified: false,
    sessionDurationMinutes: 30,
  },
  {
    email: 'helena.yoga.kids@fitmatch.dev',
    name: 'Helena Vilas Boas',
    bio: 'Yoga para crianças e adolescentes. Foco em concentração, ansiedade escolar e bem-estar emocional.',
    areaSlugs: ['YOGA', 'MEDITATION'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 10,
    averageRating: 4.95,
    totalReviews: 191,
    priceMin: 90,
    priceMax: 140,
    city: 'Belo Horizonte',
    state: 'MG',
    isVerified: true,
    sessionDurationMinutes: 45,
  },
  {
    email: 'rodrigo.personal.online@fitmatch.dev',
    name: 'Rodrigo Paiva',
    bio: 'Personal 100% online. Treinos de academia e casa com vídeo de execução e check-in semanal.',
    areaSlugs: ['PERSONAL_TRAINING'],
    modalities: [SessionModality.ONLINE],
    yearsExperience: 5,
    averageRating: 4.6,
    totalReviews: 34,
    priceMin: 75,
    priceMax: 115,
    city: 'Maceió',
    state: 'AL',
    isVerified: false,
    sessionDurationMinutes: 60,
  },
  {
    email: 'gisele.funcional.senior@fitmatch.dev',
    name: 'Gisele Barbosa',
    bio: 'Funcional para terceira idade. Foco em equilíbrio, prevenção de quedas e qualidade de vida.',
    areaSlugs: ['FUNCTIONAL_TRAINING', 'REHABILITATION'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 13,
    averageRating: 4.9,
    totalReviews: 165,
    priceMin: 120,
    priceMax: 180,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'lucas.bjj.online@fitmatch.dev',
    name: 'Lucas Arruda',
    bio: 'BJJ online via análise de vídeo. Feedbacks detalhados de técnica para praticantes que não têm academia próxima.',
    areaSlugs: ['MARTIAL_ARTS'],
    modalities: [SessionModality.ONLINE, SessionModality.HYBRID],
    yearsExperience: 9,
    averageRating: 4.75,
    totalReviews: 82,
    priceMin: 100,
    priceMax: 150,
    city: 'Uberlândia',
    state: 'MG',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'tatiane.spinning.outdoor@fitmatch.dev',
    name: 'Tatiane Cavalcante',
    bio: 'Ciclismo outdoor e indoor. Treinos em grupo na ciclovia e spinning em academia parceira.',
    areaSlugs: ['CYCLING', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 7,
    averageRating: 4.8,
    totalReviews: 93,
    priceMin: 95,
    priceMax: 145,
    city: 'Brasília',
    state: 'DF',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'fausto.pilates.masculino@fitmatch.dev',
    name: 'Fausto Gama',
    bio: 'Pilates e mobilidade para homens sedentários e atletas. Método masculino sem estigma.',
    areaSlugs: ['PILATES', 'FUNCTIONAL_TRAINING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.HYBRID],
    yearsExperience: 8,
    averageRating: 4.8,
    totalReviews: 76,
    priceMin: 130,
    priceMax: 190,
    city: 'Rio de Janeiro',
    state: 'RJ',
    isVerified: true,
    sessionDurationMinutes: 55,
  },
  {
    email: 'isabela.danca.flamenco@fitmatch.dev',
    name: 'Isabela Romero',
    bio: 'Flamenco e dança espanhola. Aulas individuais para adultos, com figurino e músicas originais.',
    areaSlugs: ['DANCE'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 16,
    averageRating: 4.9,
    totalReviews: 144,
    priceMin: 140,
    priceMax: 200,
    city: 'São Paulo',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
  {
    email: 'samuel.nutri.infantil@fitmatch.dev',
    name: 'Samuel Torres',
    bio: 'Nutrição esportiva para crianças e adolescentes. Combate obesidade infantil com abordagem lúdica.',
    areaSlugs: ['NUTRITION_COACHING'],
    modalities: [SessionModality.IN_PERSON, SessionModality.ONLINE],
    yearsExperience: 8,
    averageRating: 4.85,
    totalReviews: 101,
    priceMin: 130,
    priceMax: 190,
    city: 'Fortaleza',
    state: 'CE',
    isVerified: true,
    sessionDurationMinutes: 50,
  },
  {
    email: 'clara.swim.sp@fitmatch.dev',
    name: 'Clara Bonfim',
    bio: 'Natação masters para adultos acima de 40 anos. Técnica, condicionamento e sociabilização aquática.',
    areaSlugs: ['SWIMMING'],
    modalities: [SessionModality.IN_PERSON],
    yearsExperience: 10,
    averageRating: 4.85,
    totalReviews: 121,
    priceMin: 140,
    priceMax: 210,
    city: 'Santos',
    state: 'SP',
    isVerified: true,
    sessionDurationMinutes: 60,
  },
];

async function upsertProfessional(p: ProfSeed) {
  const user = await prisma.user.upsert({
    where: { email: p.email },
    update: { name: p.name },
    create: {
      email: p.email,
      name: p.name,
      passwordHash: SEED_PASSWORD,
      role: UserRole.PROFESSIONAL,
    },
  });

  const professional = await prisma.professional.upsert({
    where: { userId: user.id },
    update: {
      bio: p.bio,
      modalities: p.modalities,
      yearsExperience: p.yearsExperience,
      averageRating: p.averageRating,
      totalReviews: p.totalReviews,
      priceMin: p.priceMin,
      priceMax: p.priceMax,
      priceCurrency: 'BRL',
      locationCity: p.city,
      locationState: p.state,
      locationCountry: 'Brasil',
      locationStreet: 'Rua Fictícia, 100',
      locationPostal: '00000-000',
      isVerified: p.isVerified,
      isAcceptingClients: p.isAcceptingClients ?? true,
      crefNumber: p.crefNumber,
      sessionDurationMinutes: p.sessionDurationMinutes,
    },
    create: {
      userId: user.id,
      bio: p.bio,
      modalities: p.modalities,
      yearsExperience: p.yearsExperience,
      averageRating: p.averageRating,
      totalReviews: p.totalReviews,
      priceMin: p.priceMin,
      priceMax: p.priceMax,
      priceCurrency: 'BRL',
      locationCity: p.city,
      locationState: p.state,
      locationCountry: 'Brasil',
      locationStreet: 'Rua Fictícia, 100',
      locationPostal: '00000-000',
      isVerified: p.isVerified,
      isAcceptingClients: p.isAcceptingClients ?? true,
      crefNumber: p.crefNumber,
      sessionDurationMinutes: p.sessionDurationMinutes,
    },
  });

  await prisma.professionalArea.deleteMany({ where: { professionalId: professional.id } });
  for (const slug of p.areaSlugs) {
    const area = await prisma.areaAtuacao.findUnique({ where: { slug } });
    if (area) {
      await prisma.professionalArea.create({
        data: { professionalId: professional.id, areaId: area.id },
      });
    }
  }

  for (const slug of p.areaSlugs) {
    const type = slug as SpecializationType;
    await prisma.specialization.upsert({
      where: { professionalId_type: { professionalId: professional.id, type } },
      update: { yearsExperience: p.yearsExperience },
      create: {
        professionalId: professional.id,
        type,
        yearsExperience: p.yearsExperience,
        description: p.bio.slice(0, 120),
        subSpecializations: [],
      },
    });
  }

  const hasAvailability = await prisma.availability.findFirst({
    where: { professionalId: professional.id },
  });
  if (!hasAvailability) {
    const days = [1, 2, 3, 4, 5];
    const assignedDays = days.slice(0, 3 + Math.floor(Math.random() * 3));
    for (const day of assignedDays) {
      const start = new Date('2026-01-05T08:00:00.000Z');
      start.setUTCHours(9 + Math.floor(Math.random() * 8), 0, 0, 0);
      const end = new Date(start);
      end.setUTCHours(start.getUTCHours() + 1, 0, 0, 0);
      await prisma.availability.create({
        data: {
          professionalId: professional.id,
          dayOfWeek: day,
          startTime: start,
          endTime: end,
          recurrence: AvailabilityRecurrence.WEEKLY,
          validFrom: new Date('2026-01-01'),
        },
      });
    }
  }
}

async function main() {
  console.log(`Seeding ${PROFESSIONALS.length} professionals...`);

  const areas = await prisma.areaAtuacao.count();
  if (areas === 0) {
    console.error('Run npm run db:seed first to create areas.');
    process.exit(1);
  }

  let created = 0;
  for (const p of PROFESSIONALS) {
    await upsertProfessional(p);
    created++;
    if (created % 10 === 0) console.log(`  ${created}/${PROFESSIONALS.length} done...`);
  }

  console.log(`\n✓ ${created} professionals seeded successfully.`);
  const total = await prisma.professional.count();
  console.log(`Total professionals in DB: ${total}`);
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (err) => {
    console.error(err);
    await prisma.$disconnect();
    process.exit(1);
  });
